query search($searchText: String!, $language: String) {
  searchFilms(searchText: $searchText, language: $language) {
    externalId
    title
    images {
      small {
        main
        secondary
      }
      medium {
        main
        secondary
      }
      large {
        main
        secondary
      }
    }
    release_date
    overview
  }
  searchSeries(searchText: $searchText, language: $language) {
    externalId
    title
    images {
      small {
        main
        secondary
      }
      medium {
        main
        secondary
      }
      large {
        main
        secondary
      }
    }
    first_air_date
    overview
  }
}
