mutation completeSerie($id: String!) {
  completeSerie(id: $id) {
    id
    externalId
    completed
    serie {
      title
      overview
      genres {
        id
        name
      }
      popularity
      vote_count
      vote_average
      videoData {
        trailer
      }
      omdbData {
        Poster
      }
      images {
        main
        secondary
      }
    }
  }
}
