query getLists($type: String, $userId: String!) {
  lists(type: $type, userId: $userId) {
    id
    description
    name
    date
    type
    items {
      id
      externalId
      title
      images {
        small {
          main
        }
      }
    }
  }
}
