query getUserMovies($userId: String!) {
  getUserMovies(userId: $userId) {
    completed
    id
    film {
      externalId
      title
      images {
        medium {
          main
        }
        large {
          main
        }
      }
    }
  }
}
