query getUserLastItems($userId: String!) {
  getUserLastItems(userId: $userId) {
    date
    type
    item {
      id
      title
      overview
      images {
        large {
          main
          secondary
        }
      }
    }
  }
}
