query searchSeries($searchText: String!, $language: String) {
  searchSeries(searchText: $searchText, language: $language) {
    externalId
    title
    images {
      main
      secondary
    }
    first_air_date
    overview
  }
}
