mutation sendNotification(
  $type: String!
  $title: String
  $externalId: Int
  $userEmail: String!
) {
  pushNotification(
    type: $type
    title: $title
    externalId: $externalId
    userEmail: $userEmail
  ) {
    id
  }
}
