mutation addSerie($externalId: Int!) {
  addSerie(externalId: $externalId) {
    id
    externalId
    completed
    serie {
      title
      overview
      genres {
        id
        name
      }
      popularity
      vote_count
      vote_average
      videoData {
        trailer
      }
      omdbData {
        Poster
      }
      images {
        medium {
          main
          secondary
        }
        large {
          main
          secondary
        }
      }
    }
  }
}
