query getUserSeries($userId: String!) {
  getUserSeries(userId: $userId) {
    completed
    id
    serie {
      externalId
      title
      images {
        small {
          main
          secondary
        }
        medium {
          main
        }
        large {
          main
        }
      }
    }
  }
}
