mutation addItemToList($itemId: String!, $listId: String!) {
  addItemToList(itemId: $itemId, listId: $listId) {
    id
    name
    date
    type
    items {
      id
      externalId
      title
      images {
        small {
          main
        }
      }
    }
  }
}
