mutation createList(
  $name: String!
  $description: String
  $type: String!
  $items: [String]
) {
  createList(
    name: $name
    description: $description
    type: $type
    items: $items
  ) {
    id
    description
    name
    date
    type
    items {
      id
      externalId
      title
      images {
        small {
          main
        }
        medium {
          main
        }
      }
    }
  }
}
